### PR TITLE
add basedoc

### PR DESCRIPTION
**Pull request by XiaSun-Atmos**
Add base doc

### CODE REVIEW

**Review by climbfuji — CHANGES_REQUESTED** [review]
Please remove all `.DS_Store` files from the PR. Also, do we need to commit the `docs/build` directory? I don't think so, or? The documentation will be built from the contents of `docs/source`?

**Comment by XiaSun-Atmos** [comment]
You are right Dom. /build directory is not necessary. DS_Store is deleted. Thanks!

**Review by climbfuji — CHANGES_REQUESTED** [review]
Thanks. I still see some `.DS_Store` files. And the question about the `.zip` and `.pickle` files - do they need to be there?

**Comment by XiaSun-Atmos** [comment]
Thank you Dom for catching that. Please review the latest. Thanks!

**Comment by climbfuji** [comment]
Getting there ;-) I see one last `.zip` file in the PR where I am not sure if it should remain or not.

**Comment by XiaSun-Atmos** [comment]
Did you mean the UFS_Examples.zip at /docs/examples?  That is the link for the   :download:`Download all examples in Python/NCL source code: UFS_Examples.zip <../examples/UFS_Examples.zip>` in the examples section. But we can changes that if zip file is not desired. Thanks!

**Comment by climbfuji** [comment]
> Did you mean the UFS_Examples.zip at /docs/examples? That is the link for the :download:`Download all examples in Python/NCL source code: UFS_Examples.zip <../examples/UFS_Examples.zip>` in the examples section. But we can changes that if zip file is not desired. Thanks!

In this case it's okay I think, thanks for the clarification.

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
Ready to merge?

**Pull request merged**
