### PR TITLE
replace BIS case to DNR radiation inversion case

### PR DESCRIPTION
**Pull request by XiaSun-Atmos**
This PR replaces the BIS inversion case with the DNR inversion case. It's the same simulation. There were no low-level clouds observed or simulated at the DNR sounding site.

- [x] Dom, could you please upload the CAPE case IC files to s3? Location is `/home/Xia.Sun/Data/ufs-case-studies/tars/2020072300.gfs.nemsio.tar.gz`. Thanks!

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
Why replace? I would suggest to keep both cases.

**Comment by XiaSun-Atmos** [comment]
> Why replace? I would suggest to keep both cases.

The two cases are the same simulation. They are the same regional radiation case. I just switched the sounding sites. I think they belong to one case.

I initially added additional two sub-tabs to include the soundings from Denver, CO and Bismarck, ND. But I am not sure what will be a good name for this case.

**Comment by climbfuji** [comment]
I see, thanks for the explanation.

**Comment by climbfuji** [comment]
@XiaSun-Atmos I cannot access your home directory on hera (?) - can you put the data somewhere that is accessible to me please?

**Comment by XiaSun-Atmos** [comment]
@climbfuji Try this: /scratch1/BMC/gmtb/Xia.Sun/Data/ufs-case-studies/tars/2020072300.gfs.nemsio.tar.gz 
Please let me know if it doesn't work. Thanks!

**Comment by climbfuji** [comment]
> @climbfuji Try this: /scratch1/BMC/gmtb/Xia.Sun/Data/ufs-case-studies/tars/2020072300.gfs.nemsio.tar.gz
> Please let me know if it doesn't work. Thanks!

@XiaSun-Atmos can you try please if the usual download link works for you?

**Comment by XiaSun-Atmos** [comment]
Yes. The download links work well! Thank you Dom.

**Review by climbfuji — APPROVED** [review]
There are two unnecessary whitespace changes, but not a problem. Thanks for making the change!

**Pull request merged**
