### PR TITLE
Add GFS.v.16.0.10 results for 2019 Halloween Storm Case

### PR DESCRIPTION
**Pull request by XiaSun-Atmos**
Add GFS.v.16.0.10 results for 2019 Halloween Storm Case

### CODE REVIEW

**Comment by climbfuji** [comment]
@XiaSun-NOAA I see a lot of conflicts - possible that your mrw branch is not based on the latest develop?

**Comment by XiaSun-Atmos** [comment]
Hi Dom, @climbfuji  It should be good now. Thanks!

**Review by climbfuji — APPROVED** [review]
I have not tried to follow the instructions, but they look good. If @panll has some time, it would be great to check if the instructions work for him, too.

**Comment by panll** [comment]
I'll check it. @climbfuji

**Comment by panll** [comment]
Overall, it looks great to me. @climbfuji @XiaSun-NOAA 

Minor comments on section 7:

Need a simple documentation for each example script includes:
Modules loaded
Input file
Out put file
Example to run the code

For example:
1)      For ncl script
module load ncl
ncl script_name

2)      For python script
module load ananconda3-5.3.1
(with pynio pyngl netCDF4 pandas matplotlib numpy xarray)
python script_name

put a link to GFDL tracker

**Comment by XiaSun-Atmos** [comment]
Thank you @panll . This will be done at the next PR

**Pull request merged**
